use hooks

diff --git a/jobscripts/habrok/eb_configuration b/jobscripts/habrok/eb_configuration
--- a/jobscripts/habrok/eb_configuration
+++ b/jobscripts/habrok/eb_configuration
@@ -10,10 +10,9 @@ if [ -z ${REPO} ] || [ -z ${ARCH} ]; then
 fi
 export EASYBUILD_INSTALLPATH=/cvmfs/${REPO}/${OS}/${ARCH}
 
-# TODO: uncomment the following lines whenever we need hooks
-#export EASYBUILD_HOOKS=$(realpath eb_hooks.py)
-# make sure hooks are available, so we can produce a clear error message
-#if [ ! -f $EASYBUILD_HOOKS ]; then
-#  echo "Error: $EASYBUILD_HOOKS does not exist!"
-#  exit 1
-#fi
+export EASYBUILD_HOOKS=/home/${USER}/easybuild/cit-hpc-easybuild/hooks/hooks.py
+ make sure hooks are available, so we can produce a clear error message
+if [ ! -f $EASYBUILD_HOOKS ]; then
+  echo "Error: $EASYBUILD_HOOKS does not exist!"
+  exit 1
+fi
